import os
import json
import sys
from datetime import datetime, date

# Absolute paths to datasets
current_file_dir = os.path.dirname(os.path.abspath(__file__))
DATASETS_DIR = os.path.abspath(os.path.join(current_file_dir, "static", "datasets"))
USERS_FILE = os.path.join(DATASETS_DIR, "users.json")
JOURNALS_FILE = os.path.join(DATASETS_DIR, "journals.json")

# Mock Base class for models
class Base:
    metadata = None

class Row:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
            
    def __repr__(self):
        return f"Row({self.__dict__})"

def check_constraint(item, constraint):
    if not isinstance(constraint, tuple) or len(constraint) != 3:
        return bool(constraint)
        
    op, field, val = constraint
    item_val = item.get(field)
    
    # Unwrap enums or other wrapped values
    if hasattr(val, "value"):
        val = val.value
    if hasattr(item_val, "value"):
        item_val = item_val.value
        
    # Cast comparisons for id and user_id to strings to be extremely resilient
    if field in ["id", "user_id"]:
        if item_val is not None:
            item_val = str(item_val)
        if val is not None:
            if op == "in" and isinstance(val, (list, tuple, set)):
                val = [str(v) for v in val]
            else:
                val = str(val)

    if op == "eq":
        return item_val == val
    elif op == "ne":
        return item_val != val
    elif op == "in":
        if not isinstance(val, (list, tuple, set)):
            return False
        return item_val in val
    elif op == "lt":
        if item_val is None or val is None: return False
        return item_val < val
    elif op == "le":
        if item_val is None or val is None: return False
        return item_val <= val
    elif op == "gt":
        if item_val is None or val is None: return False
        return item_val > val
    elif op == "ge":
        if item_val is None or val is None: return False
        return item_val >= val
        
    return True

class JsonQuery:
    def __init__(self, data, model_class):
        self.data = list(data)
        self.model_class = model_class

    def filter(self, *criterion):
        filtered_data = []
        for item in self.data:
            match = True
            for crit in criterion:
                # If standard SQLAlchemy binary expression evaluates to a tuple rule
                if isinstance(crit, tuple):
                    if not check_constraint(item, crit):
                        match = False
                        break
                # Handle direct field references or bool filters
                elif not bool(crit):
                    match = False
                    break
            if match:
                filtered_data.append(item)
        return JsonQuery(filtered_data, self.model_class)

    def order_by(self, crit):
        # Handle tuple sorting generated by FieldRef.asc() or desc()
        field_name = "id"
        desc = False
        if isinstance(crit, tuple) and len(crit) == 2:
            direction, field_name = crit
            desc = (direction == "desc")
        elif hasattr(crit, "name"):
            field_name = crit.name
            
        def get_sort_key(item):
            val = item.get(field_name)
            # If standard string representations of dates, they sort naturally
            if isinstance(val, (date, datetime)):
                return val.isoformat()
            return val if val is not None else ""

        self.data.sort(key=get_sort_key, reverse=desc)
        return self

    def limit(self, n):
        return JsonQuery(self.data[:n], self.model_class)

    def count(self):
        return len(self.data)

    def all(self):
        if self.model_class == Row:
            return [Row(**item) for item in self.data]
        return [self.model_class(**item) for item in self.data]

    def first(self):
        if not self.data:
            return None
        if self.model_class == Row:
            return Row(**self.data[0])
        return self.model_class(**self.data[0])

class JsonDatabaseSession:
    def __init__(self):
        # 1. Load users
        if os.path.exists(USERS_FILE):
            try:
                with open(USERS_FILE, "r", encoding="utf-8") as f:
                    self.users = json.load(f)
            except Exception as e:
                print(f"[JsonDB] Error reading users.json: {e}", file=sys.stderr)
                self.users = []
        else:
            self.users = []

        # 2. Load journals
        if os.path.exists(JOURNALS_FILE):
            try:
                with open(JOURNALS_FILE, "r", encoding="utf-8") as f:
                    self.journals = json.load(f)
            except Exception as e:
                print(f"[JsonDB] Error reading journals.json: {e}", file=sys.stderr)
                self.journals = []
        else:
            self.journals = []

    def query(self, *args):
        if not args:
            raise ValueError("Query needs at least one argument")
            
        first_arg = args[0]
        
        # If querying a model class (e.g. models.User, models.Journal)
        if isinstance(first_arg, type):
            model_name = first_arg.__name__
            if model_name == "User":
                return JsonQuery(self.users, first_arg)
            elif model_name == "Journal":
                return JsonQuery(self.journals, first_arg)
                
        # If querying individual fields (e.g. db.query(User.id, User.realname))
        elif hasattr(first_arg, "name"):
            # Collect names of fields
            field_names = []
            for arg in args:
                if hasattr(arg, "name"):
                    field_names.append(arg.name)
                elif isinstance(arg, str):
                    field_names.append(arg)
            
            # Determine if this belongs to Journal or User based on common field names
            is_journal = any(fn in ["journal_date", "content", "writing_time_spend", "writing_phase"] for fn in field_names)
            data_source = self.journals if is_journal else self.users
            
            selected_data = []
            for item in data_source:
                row_dict = {fn: item.get(fn) for fn in field_names}
                selected_data.append(row_dict)
                
            return JsonQuery(selected_data, Row)
            
        raise ValueError(f"Unsupported query argument: {first_arg}")

    def close(self):
        pass
        
    def commit(self):
        pass

    def add(self, obj):
        pass

    def refresh(self, obj):
        pass

# Expose standard FastAPI dependency Injection Session type
Session = JsonDatabaseSession

def get_db():
    db = JsonDatabaseSession()
    try:
        yield db
    finally:
        db.close()